package main

import (
	"bufio"
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

type InjectTarget struct {
	PackageName string
	FuncName    string
	FieldName   string
	FieldType   string
}

type TemplateData struct {
	ModuleName      string
	Repositories    []InjectTarget
	Services        []InjectTarget
	Handlers        []InjectTarget
	BotHandlers     []InjectTarget
	WorkerHandlers  []InjectTarget
	Providers       []InjectTarget
	ProviderImports []string

	HasRepositories bool
	HasServices     bool
	HasHandlers     bool
	HasBot          bool
	HasWorkers      bool
	HasProviders    bool
}

const containerTemplate = `// Code generated by digen; DO NOT EDIT.
package container

import (
	"github.com/google/wire"

	"{{ .ModuleName }}/internal/core/config"
	"{{ .ModuleName }}/internal/core/database"
{{- if .HasRepositories }}
	"{{ .ModuleName }}/internal/repositories"
{{- end }}
{{- if .HasServices }}
	"{{ .ModuleName }}/internal/services"
{{- end }}
{{- if .HasHandlers }}
	"{{ .ModuleName }}/internal/handlers"
{{- end }}
{{- if .HasBot }}
	"{{ .ModuleName }}/internal/bot"
	bot_handlers "{{ .ModuleName }}/internal/bot/handlers"
{{- end }}
{{- if .HasWorkers }}
	worker_handlers "{{ .ModuleName }}/internal/worker/handlers"
{{- end }}
{{- range .ProviderImports }}
	"{{ . }}"
{{- end }}
)

// Auto-generated structs (Stable Base)
type Repositories struct {
{{- range .Repositories }}
	{{ .FieldName }} {{ .FieldType }}
{{- end }}
}

type Services struct {
{{- range .Services }}
	{{ .FieldName }} {{ .FieldType }}
{{- end }}
}

type Handlers struct {
{{- range .Handlers }}
	{{ .FieldName }} {{ .FieldType }}
{{- end }}
}

type BotHandlers struct {
{{- range .BotHandlers }}
	{{ .FieldName }} {{ .FieldType }}
{{- end }}
}

type WorkerHandlers struct {
{{- range .WorkerHandlers }}
	{{ .FieldName }} {{ .FieldType }}
{{- end }}
}

type Container struct {
	Config         *config.Config
	Repositories   Repositories
	Services       Services
	Handlers       Handlers
	BotHandlers    BotHandlers
	WorkerHandlers WorkerHandlers
{{- if .HasBot }}
	BotService     *bot.BotService
{{- end }}
}

// Config & Infra Providers
func ProvideJWTConfig(cfg *config.Config) *config.JWTConfig {
	return &cfg.JWT
}

// Wire Sets
var RepositorySet = wire.NewSet(
	ProvideRedisClient,
{{- range .Repositories }}
	{{ .PackageName }}.{{ .FuncName }},
{{- end }}
)

var ProviderSet = wire.NewSet(
{{- range .Providers }}
	{{ .PackageName }}.{{ .FuncName }},
{{- end }}
)

var ServiceSet = wire.NewSet(
	ProvideJWTConfig,
	database.NewBunTransactor,
{{- if .HasProviders }}
	ProviderSet,
{{- end }}
{{- range .Services }}
	{{ .PackageName }}.{{ .FuncName }},
{{- end }}
)

var HandlerSet = wire.NewSet(
{{- range .Handlers }}
	{{ .PackageName }}.{{ .FuncName }},
{{- end }}
)

var BotHandlerSet = wire.NewSet(
{{- if .HasBot }}
	bot.NewBotService,
{{- end }}
{{- range .BotHandlers }}
	{{ .PackageName }}.{{ .FuncName }},
{{- end }}
)

var WorkerHandlerSet = wire.NewSet(
{{- range .WorkerHandlers }}
	{{ .PackageName }}.{{ .FuncName }},
{{- end }}
)
`

const wireTemplate = `//go:build wireinject
// +build wireinject

package container

import (
	"{{ .ModuleName }}/internal/core/config"

	"github.com/google/wire"
	"github.com/uptrace/bun"
)

func InitializeContainer(
	db *bun.DB,
	cfg *config.Config,
) (*Container, error) {
	wire.Build(
		RepositorySet,
		ServiceSet,
		HandlerSet,
{{- if .HasBot }}
		BotHandlerSet,
{{- end }}
{{- if .HasWorkers }}
		WorkerHandlerSet,
{{- end }}

		wire.Struct(new(Repositories), "*"),
		wire.Struct(new(Services), "*"),
		wire.Struct(new(Handlers), "*"),
		wire.Struct(new(BotHandlers), "*"),
		wire.Struct(new(WorkerHandlers), "*"),
		wire.Struct(new(Container), "*"),
	)
	return &Container{}, nil
}
`

func main() {
	log.Println("⚡ Starting Dynamic DI Generation (digen)...")

	moduleName := getModuleName()
	log.Printf("📦 Detected Module: %s\n", moduleName)

	data := TemplateData{
		ModuleName: moduleName,
	}

	data.Repositories = scanDirectory("internal/repositories", "repositories")
	data.Services = scanDirectory("internal/services", "services")
	data.Handlers = scanDirectory("internal/handlers", "handlers")
	data.BotHandlers = scanDirectory("internal/bot/handlers", "bot_handlers")
	data.WorkerHandlers = scanDirectory("internal/worker/handlers", "worker_handlers")
	data.Providers, data.ProviderImports = scanProviders("internal/providers", moduleName)

	data.HasRepositories = len(data.Repositories) > 0
	data.HasServices = len(data.Services) > 0
	data.HasHandlers = len(data.Handlers) > 0
	data.HasBot = len(data.BotHandlers) > 0
	data.HasWorkers = len(data.WorkerHandlers) > 0
	data.HasProviders = len(data.Providers) > 0

	generateContainerFile(data)
	updateWireInjectFile(data)
	runWire()

	log.Println("🎉 Successfully generated full DI container!")
}

func getModuleName() string {
	file, err := os.Open("go.mod")
	if err != nil {
		return "new_project"
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module"))
		}
	}
	if err := scanner.Err(); err != nil {
		log.Printf("Warning reading go.mod: %v", err)
	}
	return "new_project"
}

func getTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + getTypeName(t.X)
	case *ast.SelectorExpr:
		return getTypeName(t.X) + "." + t.Sel.Name
	}
	return "Unknown"
}

func scanDirectory(path string, pkgName string) []InjectTarget {
	var targets []InjectTarget
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, path, nil, parser.ParseComments)
	if err != nil {
		return targets
	}

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				funcDecl, ok := decl.(*ast.FuncDecl)
				if !ok || funcDecl.Doc == nil || funcDecl.Type.Results == nil || len(funcDecl.Type.Results.List) == 0 {
					continue
				}

				for _, comment := range funcDecl.Doc.List {
					if strings.Contains(comment.Text, "@inject") {
						funcName := funcDecl.Name.Name

						fieldName := strings.TrimPrefix(funcName, "New")
						fieldName = strings.TrimSuffix(fieldName, "Service")
						fieldName = strings.TrimSuffix(fieldName, "Repository")
						fieldName = strings.TrimSuffix(fieldName, "Handler")

						rawType := getTypeName(funcDecl.Type.Results.List[0].Type)
						fieldType := ""
						if strings.HasPrefix(rawType, "*") {
							fieldType = "*" + pkgName + "." + strings.TrimPrefix(rawType, "*")
						} else {
							fieldType = pkgName + "." + rawType
						}

						targets = append(targets, InjectTarget{
							PackageName: pkgName,
							FuncName:    funcName,
							FieldName:   fieldName,
							FieldType:   fieldType,
						})
						log.Printf("💉 Injected: %s -> %s %s\n", funcName, fieldName, fieldType)
						break
					}
				}
			}
		}
	}
	return targets
}

func scanProviders(basePath string, moduleName string) ([]InjectTarget, []string) {
	var targets []InjectTarget
	var imports []string
	importSet := make(map[string]bool)

	entries, err := os.ReadDir(basePath)
	if err != nil {
		return targets, imports
	}

	for _, entry := range entries {
		if entry.IsDir() {
			pkgPath := filepath.Join(basePath, entry.Name())
			pkgName := entry.Name()

			fset := token.NewFileSet()
			pkgs, err := parser.ParseDir(fset, pkgPath, nil, parser.ParseComments)
			if err != nil {
				continue
			}

			hasInject := false
			for _, pkg := range pkgs {
				for _, file := range pkg.Files {
					for _, decl := range file.Decls {
						funcDecl, ok := decl.(*ast.FuncDecl)
						if !ok || funcDecl.Doc == nil || funcDecl.Type.Results == nil {
							continue
						}

						for _, comment := range funcDecl.Doc.List {
							if strings.Contains(comment.Text, "@inject") {
								funcName := funcDecl.Name.Name
								targets = append(targets, InjectTarget{
									PackageName: pkgName,
									FuncName:    funcName,
								})
								hasInject = true
								log.Printf("💉 Injected Provider: %s.%s\n", pkgName, funcName)
								break
							}
						}
					}
				}
			}

			if hasInject {
				fullImport := moduleName + "/" + filepath.ToSlash(pkgPath)
				if !importSet[fullImport] {
					importSet[fullImport] = true
					imports = append(imports, fullImport)
				}
			}
		}
	}

	return targets, imports
}

func generateContainerFile(data TemplateData) {
	tmpl, err := template.New("container").Parse(containerTemplate)
	if err != nil {
		log.Fatalf("Failed to parse template: %v", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		log.Fatalf("Failed to execute template: %v", err)
	}

	outputPath := filepath.Join("internal", "core", "container", "container_gen.go")
	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		log.Fatalf("Failed to write container_gen.go: %v", err)
	}
}

func updateWireInjectFile(data TemplateData) {
	tmpl, err := template.New("wire").Parse(wireTemplate)
	if err != nil {
		log.Fatalf("Failed to parse wire template: %v", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		log.Fatalf("Failed to execute wire template: %v", err)
	}

	outputPath := filepath.Join("internal", "core", "container", "wire.go")
	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		log.Fatalf("Failed to write wire.go: %v", err)
	}
}

func runWire() {
	cmd := exec.Command("wire")
	cmd.Dir = filepath.Join("internal", "core", "container")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		log.Fatalf("Wire command failed: %v", err)
	}
}
