// Code generated by digen; DO NOT EDIT.
package container

import (
	"github.com/google/wire"

	"new_project/internal/core/config"
	"new_project/internal/core/database"
	"new_project/internal/repositories"
	"new_project/internal/services"
	"new_project/internal/handlers"
	"new_project/internal/bot"
	bot_handlers "new_project/internal/bot/handlers"
)

// Auto-generated structs (Stable Base)
type Repositories struct {
	RedisCache repositories.CacheRepository
}

type Services struct {
	Media services.MediaService
}

type Handlers struct {
	Media *handlers.MediaHandler
}

type BotHandlers struct {
	Start *bot_handlers.StartHandler
}

type WorkerHandlers struct {
}

type Container struct {
	Config         *config.Config
	Repositories   Repositories
	Services       Services
	Handlers       Handlers
	BotHandlers    BotHandlers
	WorkerHandlers WorkerHandlers
	BotService     *bot.BotService
}

// Config & Infra Providers
func ProvideJWTConfig(cfg *config.Config) *config.JWTConfig {
	return &cfg.JWT
}

// Wire Sets
var RepositorySet = wire.NewSet(
	ProvideRedisClient,
	repositories.NewRedisCacheRepository,
)

var ProviderSet = wire.NewSet(
)

var ServiceSet = wire.NewSet(
	ProvideJWTConfig,
	database.NewBunTransactor,
	services.NewMediaService,
)

var HandlerSet = wire.NewSet(
	handlers.NewMediaHandler,
)

var BotHandlerSet = wire.NewSet(
	bot.NewBotService,
	bot_handlers.NewStartHandler,
)

var WorkerHandlerSet = wire.NewSet(
)
