// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/uptrace/bun"
	"new_project/internal/bot"
	handlers2 "new_project/internal/bot/handlers"
	"new_project/internal/core/config"
	"new_project/internal/handlers"
	"new_project/internal/repositories"
	"new_project/internal/services"
)

// Injectors from wire.go:

func InitializeContainer(db *bun.DB, cfg *config.Config) (*Container, error) {
	client := ProvideRedisClient(cfg)
	cacheRepository := repositories.NewRedisCacheRepository(client)
	containerRepositories := Repositories{
		RedisCache: cacheRepository,
	}
	mediaService := services.NewMediaService()
	containerServices := Services{
		Media: mediaService,
	}
	mediaHandler := handlers.NewMediaHandler(mediaService)
	containerHandlers := Handlers{
		Media: mediaHandler,
	}
	startHandler := handlers2.NewStartHandler()
	botHandlers := BotHandlers{
		Start: startHandler,
	}
	workerHandlers := WorkerHandlers{}
	botService, err := bot.NewBotService(cfg)
	if err != nil {
		return nil, err
	}
	container := &Container{
		Config:         cfg,
		Repositories:   containerRepositories,
		Services:       containerServices,
		Handlers:       containerHandlers,
		BotHandlers:    botHandlers,
		WorkerHandlers: workerHandlers,
		BotService:     botService,
	}
	return container, nil
}
