// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/media/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload a file to the server",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Media"
                ],
                "summary": "Upload a file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Folder to upload to",
                        "name": "folder",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/new_project_internal_dto.BaseResponse-dto_MediaUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.AppError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.MediaUploadResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "models.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Strongly typed code for client i18n",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ErrorCode"
                        }
                    ]
                },
                "err": {
                    "description": "Underlying wrapped error"
                },
                "message": {
                    "description": "Human-readable message in English",
                    "type": "string"
                },
                "type": {
                    "description": "Maps to HTTP status code",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ErrorType"
                        }
                    ]
                }
            }
        },
        "models.ErrorCode": {
            "type": "string",
            "enum": [
                "NOT_FOUND",
                "ALREADY_EXISTS",
                "VALIDATION_FAILED",
                "UNAUTHORIZED",
                "FORBIDDEN",
                "TOO_MANY_REQUESTS",
                "INTERNAL_ERROR",
                "INVALID_CREDENTIALS",
                "ACCOUNT_BLOCKED",
                "INVALID_DATE_RANGE",
                "INVALID_INPUT",
                "CONFLICT",
                "FOREIGN_KEY_VIOLATION"
            ],
            "x-enum-varnames": [
                "ErrCodeNotFound",
                "ErrCodeAlreadyExists",
                "ErrCodeValidationFailed",
                "ErrCodeUnauthorized",
                "ErrCodeForbidden",
                "ErrCodeTooManyRequests",
                "ErrCodeInternalError",
                "ErrCodeInvalidCredentials",
                "ErrCodeAccountBlocked",
                "ErrCodeInvalidDateRange",
                "ErrCodeInvalidInput",
                "ErrCodeConflict",
                "ErrCodeForeignKeyViolation"
            ]
        },
        "models.ErrorType": {
            "type": "string",
            "enum": [
                "NOT_FOUND",
                "CONFLICT",
                "VALIDATION",
                "UNAUTHORIZED",
                "FORBIDDEN",
                "TOO_MANY_REQUESTS",
                "INTERNAL"
            ],
            "x-enum-comments": {
                "ErrorTypeConflict": "409",
                "ErrorTypeForbidden": "403",
                "ErrorTypeInternal": "500",
                "ErrorTypeNotFound": "404",
                "ErrorTypeTooManyRequests": "429",
                "ErrorTypeUnauthorized": "401",
                "ErrorTypeValidation": "400"
            },
            "x-enum-descriptions": [
                "404",
                "409",
                "400",
                "401",
                "403",
                "429",
                "500"
            ],
            "x-enum-varnames": [
                "ErrorTypeNotFound",
                "ErrorTypeConflict",
                "ErrorTypeValidation",
                "ErrorTypeUnauthorized",
                "ErrorTypeForbidden",
                "ErrorTypeTooManyRequests",
                "ErrorTypeInternal"
            ]
        },
        "new_project_internal_dto.BaseResponse-dto_MediaUploadResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/dto.MediaUploadResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "description": "Enter your JWT token in the format \"Bearer \u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "NewProject API & Telegram Bot",
	Description:      "Universal Backend API & Telegram Bot Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
